.PHONY: clean All

All:
	@echo "----------Building project:[ Section8Challenge_2 - Debug ]----------"
	@cd "Section8Challenge_2" && "$(MAKE)" -f  "Section8Challenge_2.mk"
clean:
	@echo "----------Cleaning project:[ Section8Challenge_2 - Debug ]----------"
	@cd "Section8Challenge_2" && "$(MAKE)" -f  "Section8Challenge_2.mk" clean
